# Generated by Django 3.2.16 on 2025-01-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250111_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/image/', verbose_name='Картинка'),
        ),
    ]
